networks:
  papercut:  
    name: papercut
    external: true
  database:
  observability:
    driver: bridge

services:
  pidelo.api:
    image: ${DOCKER_REGISTRY-}presentation
    container_name: pidelo.api
    build:
      context: .
      dockerfile: src/Presentation/Dockerfile
    depends_on:
    - pidelo.elasticsearch
    - pidelo.database
    - pidelo.loki
    networks:
    - observability
    - database
    - papercut

  pidelo.database:
    image: postgres:latest
    container_name: pidelo.database
    restart: always
    environment:
      - POSTGRES_DB=pidelo
      - POSTGRES_USER=pidelo
      - POSTGRES_PASSWORD=pidelo
    volumes:
      - ./.containers/pidelo_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
     - database

  pidelo.database.admin:
    image: dpage/pgadmin4
    container_name: pidelo.database.admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pidelo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pidelo
    ports:
      - 54321:80
    depends_on:
      - pidelo.database
    networks:
     - database

  pidelo.elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    ports:
     - 9200:9200
     - 9300:9300
    volumes:
     - ./.containers/elasticsearch_data:/usr/share/elasticsearch/data
    environment:
     - cluster.name=es
     - xpack.security.enabled=false
     - xpack.watcher.enabled=false
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.type=single-node
    networks:
     - observability
   
  pidelo.kibana:
     container_name: kibana
     image: docker.elastic.co/kibana/kibana:8.15.0
     ports:
      - 5601:5601
     depends_on:
      - pidelo.elasticsearch
     environment:
      - ELASTICSEARCH_URL=http://localhost:9200
     networks:
      - observability

  pidelo.loki:
    container_name: pidelo.loki
    image: grafana/loki:2.9.2
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability

  pidelo.promtail:
    container_name: pidelo.promtail
    image: grafana/promtail:2.9.2
    volumes:
      - ./.containers/grafana:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - observability

  pidelo.grafana:
    container_name: pidelo.grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://pidelo.loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - observability